---
title: "Data Challenge 2026"
output: 
  rmdformats::material:
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, 
  warning = FALSE, 
  message = FALSE
)
```

# Introducción

Bonsai Corp es una empresa de brócoli congelado, en donde los productos se comercializan en un envase primario que contiene al alimento, y estos son colocados en cajas de cartón (envase secundario) para almacenarlos y transportarlos desde 5 plantas hacia 5 regiones distribuidas por el mundo. Esta cajas son apiladas en pallets de 1200 × 800 mm y altura máxima de carga de 1800 mm. Los envíos dentro de la misma región tienen un costo de USD 150 por pallet; los envíos a las otras cuatro regiones tienen un costo de USD 500 por pallet.

El catalogo está compuesto de 427 productos, los cuales cada uno tiene su propia caja, aunque puede existir la posibilidad de que más de un producto tenga un envase secundario con iguales dimensiones. Esta estratégia de packaging durante el último período de tiempo, produjo un catalogo de 204 tipos de cajas distintos, cada uno con su propio molde, sus propias corridas de producción y su propio stock en depósito, generando altos costos de packaging, logística e inventario. Ante cada lanzamiento de un nuevo producto, estos costos siguen en aumento, y la necesidad de hacer algo para bajarlos es imperiosa.

Imagen

# Objetivos



# Los datos

## Bases disponibles

Fueron proporcionadas 4 bases de datos con distinta información relevante para la realización de este trabajo:

-   `catalogo_productos`

El catálogo de productos es la tabla central e incluye un identificador único por SKU, su descripción comercial, peso neto por caja y la clave que lo vincula al tipo de caja asignado. 

<details>

<summary>📂 Variables</summary>

--   `codigo_producto`: id del producto.

--   `descripcion_producto`: descripción del producto.

--   `ingrediente_forma`: forma del brócoli en el producto.

--   `tipo_proyecto`:

--   `subcategoria`: 

--   `tamaño_corte`: 

--   `peso_neto_caja`: 

--   `tamaño_paquete`: 

--  `cantidad_paquetes`: 

--   `peso_neto_paquete`: 

--   `caja_tipo_id`:

</details>

<br>

-   `especificaciones_caja`

Las especificaciones de cajas contienen las dimensiones interiores y exteriores de cada tipo, junto con los parámetros de apilado en pallet. 

<details>

<summary>📂 Variables</summary>

--   `caja_tipo_id`: 

--   `caja_grosor_mm`: 

--   `caja_interior_largo`: 

--   `caja_interior_ancho`: 

--   `caja_interior_alto`: 

--   `caja_exterior_largo`: 

--   `caja_exterior_ancho`: 

--   `caja_exterior_alto`: 

--   `pallet_alto`: 

--   `pallet_ancho`: 

--   `pallet_largo`: 

--   `cantidad_cajas_alto`: 

--   `cantidad_cajas_largo`: 

--   `cantidad_cajas_ancho`: 

--   `cantidad_cajas_total`: 

--   `utilizacion`: 

</details>

<br>

-   `operaciones_planta`

Las operaciones de planta registran los volúmenes anuales por SKU y los costos logísticos asociados. 

<details>

<summary>📂 Variables</summary>

--   `codigo_producto`: 

--   `volumen_producto_canal_servicios_comida`:

--   `volumen_producto_canal_cadenas_corporativas`:

--   `volumen_producto_canal_otros`:

--   `volumen_producto_total`: 

--   `volumen_producto_planta_buenos_aires`:

--   `volumen_producto_planta_curitiba`:

--   `volumen_producto_planta_santiago`:

--   `volumen_producto_planta_monterrey`:

--   `volumen_producto_planta_bakersfield`:

--   `cantidad_pallets_planta_buenos_aires`:

--   `cantidad_pallets_planta_curitiba`:

--   `cantidad_pallets_planta_santiago`:

--   `cantidad_pallets_planta_monterrey`:

--   `cantidad_pallets_planta_bakersfield`:

--   `cantidad_pallets_total`:

--   `costo_total_planta_buenos_aires`:

--   `costo_total_planta_curitiba`:

--   `costo_total_planta_santiago`:

--   `costo_total_planta_monterrey`:

--   `costo_total_planta_bakersfield`:

--   `costo_pallets_planta_buenos_aires`:

--   `costo_pallets_planta_curitiba`:

--   `costo_pallets_planta_santiago`:

--   `costo_pallets_planta_monterrey`:

--   `costo_pallets_planta_bakersfield`:

--   `costo_pallets_total`:

--   `costo_total`:

</details>

<br>

-   `procurement_cajas`

El archivo de compras consolida los volúmenes por tipo de caja y planta, y define los precios unitarios resultantes de aplicar el grosor del cartón y el descuento por volumen correspondiente.

<details>

<summary>📂 Variables</summary>

--   `caja_tipo_id`: 

--   `volumen_tipo_planta_buenos_aires`:

--   `volumen_tipo_planta_curitiba`:

--   `volumen_tipo_planta_santiago`:

--   `volumen_tipo_planta_monterrey`: 

--   `volumen_tipo_planta_bakersfield`:

--   `costo_unitario_base`:

--   `costo_total_base`:

--   `costo_unitario_planta_buenos_aires`:

--   `costo_unitario_planta_curitiba`:

--   `costo_unitario_planta_santiago`:

--   `costo_unitario_planta_monterrey`:

--   `costo_unitario_planta_bakersfield`:

--   `descuento_planta_buenos_aires`:

--   `descuento_planta_curitiba`:

--   `descuento_planta_santiago`:

--   `descuento_planta_monterrey`:

--   `descuento_planta_bakersfield`:

--   `costo_por_pallet`:

</details>

## Perprocesamiento

### Imputación de datos faltantes

### Creación de variables

# Desarrollo

## Análisis descriptivo

## Técnicas aplicadas

## Resultados

# Conclusiones y propuestas de mejoras